In [1]:
import numpy as np

In [2]:
a = np.arange(1, 11, 2)
print(a)
type(a)

[1 3 5 7 9]


numpy.ndarray

In [3]:
b = np.array([2, 4, 6, 8, 10])
b

array([ 2,  4,  6,  8, 10])

In [4]:
c = np.zeros(5, dtype="int")
c

array([0, 0, 0, 0, 0])

In [5]:
d = np.zeros((3, 4), dtype="int")
d

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [6]:
e = np.ones((4, 2, 5), dtype='int')
e

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [7]:
np.ndim(e)

3

In [8]:
f = np.full((3, 3), 5)
f

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [9]:
np.shape(f)

(3, 3)

In [10]:
g = np.eye(3, 3, dtype='bool')
g

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [11]:
h = np.linspace(1, 50, 9, dtype='int')
h

array([ 1,  7, 13, 19, 25, 31, 37, 43, 50])

In [12]:
np.size(h)

9

In [13]:
i = np.random.rand(5)
i

array([0.9128636 , 0.69513127, 0.14335223, 0.29863799, 0.05478191])

In [14]:
type(i)

numpy.ndarray

In [15]:
j = np.random.randint(1, 99, 6)
j

array([81, 53, 26, 51, 28, 42])

In [16]:
np.shape(j)

(6,)